#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# Credentials land in the forge config dir, never in the repo.
ENV_FILE="${FORGE_ENV:-$HOME/.config/silex/forge.env}"
CONFIG_FILE="${FORGE_CONFIG:-$HOME/.config/silex/forge.config.json}"
mkdir -p "$(dirname "$ENV_FILE")" "$(dirname "$CONFIG_FILE")"
chmod 700 "$(dirname "$ENV_FILE")" 2>/dev/null || true

fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# write_env creates the file with default perms; the token lives here.
secure_env() { chmod 600 "$ENV_FILE" 2>/dev/null || true; }

# shellcheck source=/dev/null
. "$LIB_DIR/forge_common.sh"
wr() {
  local wr_cmd
  wr_cmd=$(forge_wrangler) || return 1
  case "$wr_cmd" in
    wrangler) wrangler "$@" ;;
    "npx --yes wrangler") npx --yes wrangler "$@" ;;
    *) return 1 ;;
  esac
}

banner "silex-forge — provision a forge on your Cloudflare account"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites and Cloudflare login"
say "This wizard creates a forge on *your* Cloudflare account: a Pages project,"
say "a KV namespace, and the Access policies that keep artifacts private."
note "Nothing is created without showing you first. Ctrl-C is always safe."
for b in python3 curl git; do
  command -v "$b" >/dev/null 2>&1 || fail "$b is required (Windows: use WSL)"
done
if ! forge_wrangler >/dev/null 2>&1; then
  fail "wrangler or npx is required — install Node.js, then \`npm i -g wrangler\`"
fi
WHOAMI_TMP="$(mktemp)"
if ! wr whoami >"$WHOAMI_TMP" 2>&1; then
  step "Log in to Cloudflare in the browser window that opens."
  wr login || fail "wrangler login failed"
  wr whoami >"$WHOAMI_TMP" 2>&1 || fail "still not logged in"
fi
sed -E 's/[0-9a-f]{28}/…/' "$WHOAMI_TMP" | grep -iE 'logged in|Account Name|│' | head -6
CF_ACCOUNT=$(PYTHONPATH="$LIB_DIR" python3 -c \
  'import sys; from discover import account_id_from_whoami; print(account_id_from_whoami(sys.stdin.read()))' \
  < "$WHOAMI_TMP")
rm -f "$WHOAMI_TMP"
[ -n "$CF_ACCOUNT" ] || fail "could not read an account id from \`wrangler whoami\`"
say "Account: ${CF_ACCOUNT:0:8}…"
confirm "Is that the account the forge should live on?" || fail "run \`wrangler login\` with the right account, then re-run"
write_env CLOUDFLARE_ACCOUNT_ID "$CF_ACCOUNT"
secure_env

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Name the forge"
say "The public host is where your team will read artifacts."
note "It must be a domain you control, e.g. forge.acme.com"
ask PUBLIC_HOST "Public host (no https://):"
[ -n "$PUBLIC_HOST" ] || fail "a public host is required"
case "$PUBLIC_HOST" in
  *[!A-Za-z0-9.-]*) fail "invalid characters in hostname: $PUBLIC_HOST" ;;
  *.*) ;;
  *) fail "that does not look like a hostname: $PUBLIC_HOST" ;;
esac
ask FORGE_PAGES_PROJECT "Cloudflare Pages project name [silex-forge]:"
[ -n "$FORGE_PAGES_PROJECT" ] || FORGE_PAGES_PROJECT="silex-forge"
case "$FORGE_PAGES_PROJECT" in *[!a-z0-9-]*) fail "Pages names allow lowercase letters, digits and dashes only" ;; esac
write_env PUBLIC_HOST "$PUBLIC_HOST"
write_env FORGE_PAGES_PROJECT "$FORGE_PAGES_PROJECT"
secure_env

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the Pages project"
_list="$(mktemp)"
_lerr="$(mktemp)"
if ! wr pages project list >"$_list" 2>"$_lerr"; then
  rm -f "$_list" "$_lerr"
  fail "could not list Pages projects — run \`wrangler login\` (needs pages scope)"
fi
_cls="$(
  PYTHONPATH="$LIB_DIR${PYTHONPATH:+:$PYTHONPATH}" python3 -c '
import sys
from discover import classify_pages_projects
kind, others = classify_pages_projects(sys.stdin.read(), sys.argv[1])
print(kind)
for name in others:
    print(name)
' "$FORGE_PAGES_PROJECT" < "$_list"
)" || { rm -f "$_list" "$_lerr"; fail "could not parse Pages project list"; }
rm -f "$_list" "$_lerr"
_kind=$(printf '%s\n' "$_cls" | sed -n '1p')
_others=$(printf '%s\n' "$_cls" | sed '1d')
case "$_kind" in
  hit)
    say "Project '$FORGE_PAGES_PROJECT' already exists — reusing it."
    ;;
  others)
    say "This account already has Pages projects:"
    printf '%s\n' "$_others" | sed 's/^/    /'
    warn "Creating '$FORGE_PAGES_PROJECT' would add a second project."
    note "Attach an existing forge: forge-discover.sh --project NAME"
    confirm "Create an additional Pages project '$FORGE_PAGES_PROJECT'?" \
      || fail "aborted — use forge-discover.sh --project NAME"
    wr pages project create "$FORGE_PAGES_PROJECT" --production-branch=main \
      || fail "could not create the Pages project"
    ;;
  empty)
    say "Creating Pages project '$FORGE_PAGES_PROJECT' (Direct Upload, production branch main)."
    confirm "Create it now?" || fail "aborted"
    wr pages project create "$FORGE_PAGES_PROJECT" --production-branch=main \
      || fail "could not create the Pages project"
    ;;
  unparsed)
    fail "could not parse Pages project list — not creating a new forge"
    ;;
  *) fail "unexpected Pages list classify: ${_kind:-empty}" ;;
esac
pause "Done. Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the KV namespace for share links"
say "Share links (/s/<slug>/<key>/) and per-artifact visibility live in KV."
KV_ID=$(_existing FORGE_SHARES_KV_ID || true)
if [ -n "$KV_ID" ]; then
  say "Already configured: ${KV_ID:0:8}…"
else
  confirm "Create a KV namespace bound as SHARES?" || fail "aborted"
  KV_OUT=$(wr kv namespace create SHARES 2>&1) || { printf '%s\n' "$KV_OUT"; fail "KV creation failed"; }
  KV_ID=$(printf '%s' "$KV_OUT" | grep -oE '[0-9a-f]{32}' | head -1)
  [ -n "$KV_ID" ] || { printf '%s\n' "$KV_OUT"; fail "could not read the namespace id from wrangler output"; }
fi
write_env FORGE_SHARES_KV_ID "$KV_ID"
secure_env

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare API token"
say "Publishing needs an API token. OAuth alone is not enough for deploys."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Custom token."
step "Permissions: Account · Cloudflare Pages · Edit"
step "             Account · Workers KV Storage · Edit"
step "             Account · Account Settings · Read"
step "Account Resources: include the account you confirmed in stage 1."
step "Create, then copy the token — Cloudflare shows it once."
ask_secret CLOUDFLARE_API_TOKEN "Paste the token:"
[ -n "$CLOUDFLARE_API_TOKEN" ] || fail "a token is required to deploy"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
secure_env
note "Stored in $ENV_FILE (chmod 600). Never commit this file."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Point your domain at the Pages project"
say "The forge must answer on $PUBLIC_HOST, not only on *.pages.dev."
warn "This stage is manual: your domain is not a Cloudflare zone yet."
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "If the domain is not on Cloudflare yet: Add a site, then move its"
step "nameservers at your registrar. Propagation can take a while."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/${FORGE_PAGES_PROJECT}/domains"
step "Pages project → Custom domains → Set up a custom domain → $PUBLIC_HOST"
step "Accept the CNAME record Cloudflare proposes (proxied)."
pause "Press Enter once the custom domain shows as Active."
if curl -sI --max-time 15 "https://${PUBLIC_HOST}/" >/dev/null 2>&1; then
  say "$PUBLIC_HOST resolves."
else
  warn "$PUBLIC_HOST does not answer yet — DNS may still be propagating."
  SKIPPED+=("verify https://${PUBLIC_HOST}/ resolves once DNS propagates")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Zero Trust team domain"
say "Access is what keeps artifacts private. It needs a Zero Trust team."
open_url "https://one.dash.cloudflare.com/"
step "Pick a team name if you have never used Zero Trust on this account."
step "Your team domain then looks like <team>.cloudflareaccess.com"
step "Settings → Authentication: add at least one login method for your team."
ask CF_ACCESS_TEAM_DOMAIN "Team domain (<team>.cloudflareaccess.com):"
case "$CF_ACCESS_TEAM_DOMAIN" in
  *.cloudflareaccess.com) ;;
  *) fail "expected something ending in .cloudflareaccess.com" ;;
esac
write_env CF_ACCESS_TEAM_DOMAIN "$CF_ACCESS_TEAM_DOMAIN"
secure_env

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Access application: login"
say "This app issues the JWT cookie the forge reads to recognise your team."
open_url "https://one.dash.cloudflare.com/?to=/:account/access/apps/new"
step "Add an application → Self-hosted."
step "Application domain: ${PUBLIC_HOST}   path: login"
step "Add a policy: Action Allow, include your team's emails or IdP group."
step "Save, reopen the application, and copy its Application Audience (AUD) tag."
ask CF_ACCESS_AUD "Paste the login application AUD:"
[ -n "$CF_ACCESS_AUD" ] || fail "the AUD is required — Functions fail closed without it"
write_env CF_ACCESS_AUD "$CF_ACCESS_AUD"
secure_env

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Local artifact folder"
say "Artifact HTML is the source of truth and lives on your machine, not in git."
ask FORGE_HUB_ROOT "Absolute path to the folder that will hold artifacts:"
case "$FORGE_HUB_ROOT" in /*) ;; *) fail "an absolute path is required" ;; esac
mkdir -p "$FORGE_HUB_ROOT/artifacts/welcome"
if [ ! -f "$FORGE_HUB_ROOT/artifacts/welcome/index.html" ]; then
  cat > "$FORGE_HUB_ROOT/artifacts/welcome/index.html" <<'HTML'
<!doctype html>
<meta charset="utf-8">
<title>Forge is live</title>
<style>body{font:16px/1.6 system-ui;margin:12vh auto;max-width:34rem;padding:0 1rem}</style>
<h1>Forge is live</h1>
<p>This placeholder proves the deploy path works. Publish a real artifact with
<code>publish.sh &lt;slug&gt; ./file.html --title "…"</code>, then delete this one.</p>
HTML
fi
CONFIG_FILE="$CONFIG_FILE" FORGE_HUB_ROOT="$FORGE_HUB_ROOT" PUBLIC_HOST="$PUBLIC_HOST" \
FORGE_PAGES_PROJECT="$FORGE_PAGES_PROJECT" python3 - <<'PY'
import json, os
from pathlib import Path
p = Path(os.environ["CONFIG_FILE"])
cfg = json.loads(p.read_text(encoding="utf-8")) if p.is_file() else {}
cfg.update({
    "version": 1,
    "hub_root": os.environ["FORGE_HUB_ROOT"],
    "artifacts_dir": "artifacts",
    "site_dir": "site",
    "registry_dir": "registry",
    "internal_prefix": "a",
    "public_host": os.environ["PUBLIC_HOST"],
    "pages_project": os.environ["FORGE_PAGES_PROJECT"],
    # Not the Silex vault layout: no marker directories to check.
    "vault_markers": [],
})
cfg.setdefault("forge_repo", "https://github.com/go-silex/silex-forge.git")
p.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"  ✓ wrote {p}")
PY

# ── 10 ────────────────────────────────────────────────────────────────────
stage "First deploy — fail closed before opening anything"
warn "Order matters. The Functions must be live and refusing anonymous reads"
warn "BEFORE any Bypass policy exists. Bypass first would publish every artifact."
say "Deploying the engine plus your placeholder artifact."
confirm "Deploy now?" || fail "aborted"
set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a
bash "$SCRIPT_DIR/publish.sh" --rebuild-index || fail "deploy failed — fix the error above and re-run this wizard"
say "Checking the deployed Functions…"
ACL=$(curl -sI --max-time 20 "https://${PUBLIC_HOST}/a/welcome/" | tr -d '\r' | grep -i '^x-forge-acl:' || true)
if [ -n "$ACL" ]; then
  say "Functions are live: $ACL"
else
  warn "no x-forge-acl header seen on https://${PUBLIC_HOST}/a/welcome/"
  confirm "Continue anyway? Answer no if DNS is still propagating." || fail "re-run once the host answers"
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Access: open the Functions-gated paths, lock down pages.dev"
say "Now — and only now — the paths the Functions guard can bypass Access."
open_url "https://one.dash.cloudflare.com/?to=/:account/access/apps/new"
step "Add an application → Self-hosted → domain ${PUBLIC_HOST}."
step "Add these paths to the same app: /   /a/*   /s/*   /api/*"
step "Policy: Action Bypass, include Everyone."
note "The Functions still enforce visibility; private stays private."
pause "Press Enter when the Bypass application is saved."
step "Add one more application → Self-hosted → ${FORGE_PAGES_PROJECT}.pages.dev"
step "Policy: Action Allow, your team only. The preview origin must never be public."
pause "Press Enter when the pages.dev application is saved."

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Verify"
set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a
bash "$SCRIPT_DIR/forge-doctor.sh" --online || warn "doctor reported issues above"
say ""
say "Smoke tests:"
code() { curl -sS -o /dev/null -w '%{http_code}' --max-time 20 "$1" 2>/dev/null || echo "---"; }
say "  /login              → $(code "https://${PUBLIC_HOST}/login")   expect 302 (Access)"
say "  /a/welcome/         → $(code "https://${PUBLIC_HOST}/a/welcome/")   expect 302 without a cookie"
say "  pages.dev           → $(code "https://${FORGE_PAGES_PROJECT}.pages.dev/")   expect 403 or 302"
note "A 200 on /a/welcome/ without logging in means Bypass was applied too widely."
say ""
say "Publish from now on:"
note "  publish.sh <slug> ./file.html --title \"…\""
note "  publish.sh --share <slug>     # keyed link, no login"

finish
